### PR TITLE
Multipage bio (kernel 5.1+) fix

### LINKED ISSUE #186: Error tracing bio for snapshot, Linux 5.1
5.1.5-300.fc30.x86_64, XFS
```
./app/dbdctl setup-snapshot /dev/mapper/fedora-root /cow.snap 0
dd if=/dev/urandom of=/root/urand bs=1M count=256
```
```
[ 1655.422040] general protection fault: 0000 [#1] SMP PTI
[ 1655.422084] CPU: 0 PID: 26393 Comm: datto_snap_cow0 Tainted: G           OE     5.1.5-300.fc30.x86_64 #1
[ 1655.422151] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 1.12.0-2.fc30 04/01/2014
[ 1655.422205] RIP: 0010:memcpy_erms+0x6/0x10
[ 1655.422232] Code: 90 90 90 90 eb 1e 0f 1f 00 48 89 f8 48 89 d1 48 c1 e9 03 83 e2 07 f3 48 a5 89 d1 f3 a4 c3 66 0f 1f 44 00 00 48 89 f8 48 89 d1 <f3> a4 c3 0f 1f 80 00 00 00 00 48 89 f8 48 83 fa 20 72 7e 40 38 fe
[ 1655.422334] RSP: 0018:ffff99e240ee3b30 EFLAGS: 00010206
[ 1655.422366] RAX: ffff8c950cc69000 RBX: 0000000000001000 RCX: 0000000000001000
[ 1655.422407] RDX: 0000000000001000 RSI: 000c5f88075cf000 RDI: ffff8c950cc69000
[ 1655.422447] RBP: ffff8c950cc69000 R08: 0000000007acb000 R09: ffff99e240ee3b2c
[ 1655.422488] R10: 0000000000000000 R11: ffff99e240ee3d40 R12: 0000000000001000
[ 1655.422529] R13: ffff99e240ee3d30 R14: 0000000000001000 R15: 0000000000001000
[ 1655.422571] FS:  0000000000000000(0000) GS:ffff8c953da00000(0000) knlGS:0000000000000000
[ 1655.422616] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 1655.422650] CR2: 000055923a795260 CR3: 000000005ec36004 CR4: 0000000000160ef0
[ 1655.422697] Call Trace:
[ 1655.422720]  iov_iter_copy_from_user_atomic+0x185/0x380
[ 1655.422755]  iomap_write_actor+0xc0/0x190
[ 1655.422788]  iomap_apply+0xc3/0x140
[ 1655.422812]  ? iomap_zero_range_actor+0x1c0/0x1c0
[ 1655.422843]  iomap_file_buffered_write+0x5c/0x80
[ 1655.422872]  ? iomap_zero_range_actor+0x1c0/0x1c0
[ 1655.422951]  xfs_file_buffered_aio_write+0xd2/0x340 [xfs]
[ 1655.422988]  new_sync_write+0x11b/0x180
[ 1655.423013]  vfs_write+0xb6/0x1a0
[ 1655.423035]  kernel_write+0x2c/0x40
[ 1655.423061]  file_io+0x3f/0xa0 [dattobd]
[ 1655.423089]  snap_cow_thread+0x5d9/0x970 [dattobd]
[ 1655.423120]  ? __schedule+0x2c1/0x890
[ 1655.423197]  ? finish_wait+0x80/0x80
[ 1655.423222]  kthread+0xfb/0x130
[ 1655.423245]  ? ioctl_transition_inc+0x320/0x320 [dattobd]
[ 1655.423277]  ? kthread_park+0x90/0x90
[ 1655.423302]  ret_from_fork+0x35/0x40
[ 1655.423325] Modules linked in: dattobd(OE) loop ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 ipt_REJECT nf_reject_ipv4 xt_conntrack ebtable_nat ip6table_nat ip6table_mangle ip6table_raw ip6table_security iptable_nat nf_nat iptable_mangle iptable_raw iptable_security nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 ip_set nfnetlink ebtable_filter ebtables ip6table_filter ip6_tables iptable_filter ip_tables sunrpc kvm_intel kvm irqbypass crct10dif_pclmul crc32_pclmul iTCO_wdt iTCO_vendor_support ghash_clmulni_intel joydev virtio_balloon lpc_ich i2c_i801 xfs libcrc32c qxl drm_kms_helper ttm crc32c_intel drm serio_raw virtio_net virtio_console net_failover virtio_scsi failover qemu_fw_cfg [last unloaded: dattobd]
[ 1655.423706] ---[ end trace c76471ccbbb40f9c ]---
[ 1655.423737] RIP: 0010:memcpy_erms+0x6/0x10
[ 1655.423763] Code: 90 90 90 90 eb 1e 0f 1f 00 48 89 f8 48 89 d1 48 c1 e9 03 83 e2 07 f3 48 a5 89 d1 f3 a4 c3 66 0f 1f 44 00 00 48 89 f8 48 89 d1 <f3> a4 c3 0f 1f 80 00 00 00 00 48 89 f8 48 83 fa 20 72 7e 40 38 fe
[ 1655.423880] RSP: 0018:ffff99e240ee3b30 EFLAGS: 00010206
[ 1655.423912] RAX: ffff8c950cc69000 RBX: 0000000000001000 RCX: 0000000000001000
[ 1655.423953] RDX: 0000000000001000 RSI: 000c5f88075cf000 RDI: ffff8c950cc69000
[ 1655.423993] RBP: ffff8c950cc69000 R08: 0000000007acb000 R09: ffff99e240ee3b2c
[ 1655.425530] R10: 0000000000000000 R11: ffff99e240ee3d40 R12: 0000000000001000
[ 1655.427027] R13: ffff99e240ee3d30 R14: 0000000000001000 R15: 0000000000001000
[ 1655.428495] FS:  0000000000000000(0000) GS:ffff8c953da00000(0000) knlGS:0000000000000000
[ 1655.429952] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 1655.430744] CR2: 000055923a795260 CR3: 000000005ec36004 CR4: 0000000000160ef0
[ 1655.435161] datto: error tracing bio for snapshot: -14
```

5.1.7-300.fc30.x86_64, ext4
```
./app/dbdctl setup-snapshot /dev/loop0 /mnt/cow.snap 0
dd if=/dev/zero of=/mnt/zero bs=1M count=256
```
```
[ 1228.779676] BUG: unable to handle kernel paging request at ffff8892746c0000
[ 1228.779710] #PF error: [normal kernel read fault]
[ 1228.779722] PGD 4be01067 P4D 4be01067 PUD 0 
[ 1228.779734] Oops: 0000 [#1] SMP PTI
[ 1228.779744] CPU: 1 PID: 1576 Comm: datto_snap_cow0 Tainted: G           OE     5.1.7-300.fc30.x86_64 #1
[ 1228.779765] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 1.12.0-2.fc30 04/01/2014
[ 1228.779788] RIP: 0010:memcpy_erms+0x6/0x10
[ 1228.779798] Code: 90 90 90 90 eb 1e 0f 1f 00 48 89 f8 48 89 d1 48 c1 e9 03 83 e2 07 f3 48 a5 89 d1 f3 a4 c3 66 0f 1f 44 00 00 48 89 f8 48 89 d1 <f3> a4 c3 0f 1f 80 00 00 00 00 48 89 f8 48 83 fa 20 72 7e 40 38 fe
[ 1228.779838] RSP: 0018:ffff9d6380c0fbd0 EFLAGS: 00010286
[ 1228.779851] RAX: ffff889152522000 RBX: 0000000000001000 RCX: 0000000000001000
[ 1228.779867] RDX: 0000000000001000 RSI: ffff8892746c0000 RDI: ffff889152522000
[ 1228.779883] RBP: ffff889152522000 R08: 0000000000000000 R09: ffff889163b450d0
[ 1228.779899] R10: 0000000000000000 R11: ffff9d6380c0fd40 R12: 0000000000001000
[ 1228.779915] R13: ffff9d6380c0fd30 R14: 0000000000001000 R15: ffffffff92e349c0
[ 1228.779931] FS:  0000000000000000(0000) GS:ffff88917db00000(0000) knlGS:0000000000000000
[ 1228.779949] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 1228.779962] CR2: ffff8892746c0000 CR3: 0000000063490002 CR4: 0000000000160ee0
[ 1228.779982] Call Trace:
[ 1228.779993]  iov_iter_copy_from_user_atomic+0x185/0x380
[ 1228.780009]  generic_perform_write+0xe1/0x1c0
[ 1228.780016] datto: error tracing bio for snapshot: -14
[ 1228.780022]  __generic_file_write_iter+0xf9/0x1d0
[ 1228.780047]  ext4_file_write_iter+0xc6/0x3b0
[ 1228.780060]  new_sync_write+0x11b/0x180
[ 1228.780071]  vfs_write+0xb6/0x1a0
[ 1228.780081]  kernel_write+0x2c/0x40
[ 1228.780093]  file_io+0x3f/0xa0 [dattobd]
[ 1228.780109]  snap_cow_thread+0x5d9/0x970 [dattobd]
[ 1228.780127]  ? __schedule+0x2c1/0x890
[ 1228.780140]  ? finish_wait+0x80/0x80
[ 1228.780153]  kthread+0xfb/0x130
[ 1228.780166]  ? ioctl_transition_inc+0x320/0x320 [dattobd]
[ 1228.780182]  ? kthread_park+0x90/0x90
[ 1228.780195]  ret_from_fork+0x35/0x40
[ 1228.780207] Modules linked in: dattobd(OE) loop ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 ipt_REJECT nf_reject_ipv4 xt_conntrack ebtable_nat ip6table_nat ip6table_mangle ip6table_raw ip6table_security iptable_nat nf_nat iptable_mangle iptable_raw iptable_security nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 ip_set nfnetlink ebtable_filter ebtables ip6table_filter ip6_tables iptable_filter ip_tables sunrpc kvm_intel kvm irqbypass crct10dif_pclmul crc32_pclmul iTCO_wdt iTCO_vendor_support ghash_clmulni_intel virtio_balloon joydev i2c_i801 lpc_ich xfs libcrc32c qxl drm_kms_helper ttm crc32c_intel drm serio_raw virtio_console virtio_scsi virtio_net net_failover failover qemu_fw_cfg
[ 1228.780375] CR2: ffff8892746c0000
[ 1228.781023] ---[ end trace 8836b049d04583cb ]---
[ 1228.781604] RIP: 0010:memcpy_erms+0x6/0x10
[ 1228.782184] Code: 90 90 90 90 eb 1e 0f 1f 00 48 89 f8 48 89 d1 48 c1 e9 03 83 e2 07 f3 48 a5 89 d1 f3 a4 c3 66 0f 1f 44 00 00 48 89 f8 48 89 d1 <f3> a4 c3 0f 1f 80 00 00 00 00 48 89 f8 48 83 fa 20 72 7e 40 38 fe
[ 1228.783367] RSP: 0018:ffff9d6380c0fbd0 EFLAGS: 00010286
[ 1228.784032] RAX: ffff889152522000 RBX: 0000000000001000 RCX: 0000000000001000
[ 1228.784624] RDX: 0000000000001000 RSI: ffff8892746c0000 RDI: ffff889152522000
[ 1228.785236] RBP: ffff889152522000 R08: 0000000000000000 R09: ffff889163b450d0
[ 1228.785890] R10: 0000000000000000 R11: ffff9d6380c0fd40 R12: 0000000000001000
[ 1228.786460] R13: ffff9d6380c0fd30 R14: 0000000000001000 R15: ffffffff92e349c0
[ 1228.787063] FS:  0000000000000000(0000) GS:ffff88917db00000(0000) knlGS:0000000000000000
[ 1228.787628] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 1228.788213] CR2: ffff8892746c0000 CR3: 0000000063490002 CR4: 0000000000160ee0
```

### PR DESCRIPTION
**Pull request by dakotarwilliams**
Fixes #186 

This bumps the number of traced `bio_sects` so we can process larger bios, which was the observed problem with "error tracing bio for snapshot: -14". There was also a size reset which is not valid any more, and would cause the machine to lock on a cow file overrun.

### CODE REVIEW

File: src/dattobd.c [hunk 1]
```diff
@@ -2883,11 +2883,6 @@ static void __on_bio_read_complete(struct bio *bio, int err){
 		goto error;
 	}
 
-	for(i = 0; i < bio->bi_vcnt; i++){
-		bio->bi_io_vec[i].bv_len = PAGE_SIZE;
-		bio->bi_io_vec[i].bv_offset = 0;
```
Comment (nixomose) [inline src/dattobd.c]: so does somebody set these to the correct value each time on the way in? Are you sure this is true for older kernels?
you might wanna make a feature test for this and only skip it if the kernel supports multipage bios.
Always defer to tom, but I'm guessing this reset was necessary for older kernels?

Comment (dakotarwilliams) [reply src/dattobd.c]: Spoke to Tom, has to do with pre-bvec-iterator kernels. On those versions, reading causes `offset` to increase and `len` to decrease. This loop resets those positions before we pass it on. After bvec iterators (3.14), it's unnecessary. Will fix.

**Comment by chrissprague** [comment]
Built and tested a backup on `5.2.14-200.fc30.x86_64`, worked for me

**Comment by dakotarwilliams** [comment]
Tested on 2.6.32, 3.10.0, 3.16.0, 4.18.0, 5.1.20, 5.3.0-rc8. All pass tests and manual operation
